export const subjectConstants = {
    CREATE_REQUEST: 'SUBJECT_CREATE_REQUEST',
    CREATE_SUCCESS: 'SUBJECT_CREATE_SUCCESS',
    CREATE_FAILURE: 'SUBJECT_CREATE_FAILURE',

    UPDATE_REQUEST: 'SUBJECT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'SUBJECT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'SUBJECT_UPDATE_FAILURE',

    GETALL_REQUEST: 'SUBJECT_GETALL_REQUEST',
    GETALL_SUCCESS: 'SUBJECT_GETALL_SUCCESS',
    GETALL_FAILURE: 'SUBJECT_GETALL_FAILURE',

    DELETE_REQUEST: 'SUBJECT_DELETE_REQUEST',
    DELETE_SUCCESS: 'SUBJECT_DELETE_SUCCESS',
    DELETE_FAILURE: 'SUBJECT_DELETE_FAILURE',

    TOGGLE_CREATE_MODAL: 'SUBJECT_TOGGLE_CREATE_MODAL'
}